"""
Generate SQLAlchemy ORM models.

Utility script for  HiPerHealth that inspects Pydantic models
(from both `fhir_models` and `custom_models`) and produces a basic
SQLAlchemy 2.x ORM layer with one table per Pydantic class.

Usage:
    python generate_orm_models.py

Output:
    Overwrites/creates `telehealthcare_ai/db/orm_models.py`
    with autogenerated Declarative mapping code.

Notes
-----
* Only scalar field types (str, int, float, bool, datetime) and simple
  collections are handled automatically. Complex nested objects will be
  serialised into JSON columns.
* Relationships (foreign keys) are not inferred; add them manually.
* Requires pydantic>=2.0, SQLAlchemy>=2.0.
"""

from __future__ import annotations

import argparse
import sys

from datetime import date, datetime
from pathlib import Path
from typing import Any, Dict, Type

from formatting import run_ruff
from gen_base import is_concrete_model, iter_pydantic_models
from pydantic import BaseModel

# Target file to (over)write
OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent.parent
    / 'src'
    / 'hiperhealth'
    / 'models'
    / 'sqla'
    / 'fhirx.py'
)


TYPE_MAP = {
    str: 'String',
    int: 'Integer',
    float: 'Float',
    bool: 'Boolean',
    datetime: 'DateTime',
    date: 'Date',
}

# Fallback SQLAlchemy type for arbitrary / nested data
FALLBACK_TYPE = 'JSON'


def python_type_to_sqla(annotation: Any) -> tuple[str, str]:
    """
    Return a pair ``(sqlalchemy_type_name, python_hint_string)``.

    * Scalars map to a concrete SA type and their own type-name hint
      (e.g. ``("String", "str")``).
    * Lists / dicts / unknown objects fall back to JSON + ``Any``.
    """
    origin = getattr(annotation, '__origin__', None)

    # Generic collections → JSON
    if origin in (list, dict):
        return FALLBACK_TYPE, 'Any'

    # Exact scalar matches
    if annotation in TYPE_MAP:
        return TYPE_MAP[annotation], annotation.__name__

    #   sqlalchemy.DateTime  ←  datetime | Arrow | pendulum types
    if annotation is datetime:
        return 'DateTime', 'datetime'

    # Anything else → JSON
    return FALLBACK_TYPE, 'Any'


def generate_sqla_model(name: str, model_cls: Type[BaseModel]) -> str:
    """Return the SQLAlchemy declarative model as source code."""
    lines: list[str] = []
    lines.append('@public')
    lines.append(f'class {name}(Base):')
    lines.append(f'    """{name} autogenerated."""\n')
    lines.append(f"    __tablename__ = '{name.lower()}'")
    lines.append('')

    fields = model_cls.model_fields

    id_field = fields.get('id')
    inject_uuid_pk = (
        id_field is None
        or python_type_to_sqla(id_field.annotation)[0] == FALLBACK_TYPE
    )

    if inject_uuid_pk:
        lines.append(
            '    id: Mapped[str] = mapped_column('
            'String(36), primary_key=True, '
            'default=lambda: str(uuid.uuid4()))'
        )

    for field_name, field_info in fields.items():
        # skip original id when surrogate already added
        if inject_uuid_pk and field_name == 'id':
            continue

        sa_type, py_hint = python_type_to_sqla(field_info.annotation)
        nullable = not field_info.is_required()
        is_pk = field_name == 'id' and not inject_uuid_pk

        col_args = [
            sa_type,
            'primary_key=True' if is_pk else None,
            'nullable=True' if nullable else None,
            'index=True' if not is_pk else None,
        ]
        col_args = ', '.join(arg for arg in col_args if arg)

        default_token = 'None' if nullable else '...'

        lines.append(
            f'    {field_name}: Mapped[{py_hint}] = mapped_column('
            f'{col_args}, default={default_token})'
            if field_name != 'id'
            else (
                f'    {field_name}: Mapped[{py_hint}] = '
                f'mapped_column({col_args})'
            )
        )

    lines.append('')
    return '\n'.join(lines)


def build_orm_file(models: Dict[str, Type[BaseModel]]) -> str:
    """Compose the full orm_models.py content."""
    header = """\"\"\"Autogenerated ORM models from Pydantic schemas.

DO NOT EDIT MANUALLY. Regenerate via `python generate_orm_models.py`.
\"\"\"

from __future__ import annotations

from datetime import datetime
import uuid

from typing import Any, Literal, Optional, Union  # noqa

from fhir.resources.fhirtypes import (
    ReferenceType,
    CodeableConceptType,
)
from public import public
from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Float,
    Integer,
    JSON,
    String,
    Text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


@public
class Base(DeclarativeBase):
    \"\"\"Declarative base for  HiPerHealth.\"\"\"
    pass

"""
    body = []
    for model_cls in models.values():
        if not is_concrete_model(model_cls):
            continue
        body += [
            '@public\n' + generate_sqla_model(model_cls.__name__, model_cls)
        ]

    return header + '\n\n'.join(body) + '\n'


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse CLI arguments for SQLAlchemy model generation."""
    parser = argparse.ArgumentParser(
        description='Generate SQLAlchemy ORM models from Pydantic schemas.'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Print generated output to stdout without writing files.',
    )
    parser.add_argument(
        '--output',
        type=str,
        help='Write generated output to a custom file path.',
    )
    return parser.parse_args(argv)


def resolve_output_path(raw_output: str | None) -> Path:
    """Resolve and validate the output path from CLI input."""
    if not raw_output:
        return OUTPUT_PATH

    candidate = Path(raw_output).expanduser()
    if candidate.exists() and candidate.is_dir():
        raise ValueError(f'Output path points to a directory: {candidate}')

    return candidate


def write_generated_code(output_path: Path, generated_code: str) -> None:
    """Write generated ORM code to a file, creating parent directories."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generated_code, encoding='utf-8')


def main(argv: list[str] | None = None) -> int:
    """Execute the CLI."""
    args = parse_args(argv)
    models = iter_pydantic_models()
    generated_code = build_orm_file(models)

    if args.dry_run:
        print(generated_code, end='')
        return 0

    try:
        output_path = resolve_output_path(args.output)
        write_generated_code(output_path, generated_code)
    except (OSError, ValueError) as err:
        print(f'[x] Failed to write ORM models: {err}', file=sys.stderr)
        return 1

    print(f'[✓] ORM models written to {output_path}')

    try:
        run_ruff(output_path, fix=True)
    except RuntimeError as err:
        # Fallback: continue without failing the generator
        print(f'[!] Ruff step skipped: {err}')

    return 0


if __name__ == '__main__':
    sys.exit(main())
