name: hiperhealth
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.10,<=3.13
  - pip
  - nodejs # used by semantic-release
  - tesseract
  - libmagic
  - uv
  - pip:
      - setuptools >=70.1.0,<72
      - paginate==0.5.6 # distlib issue
